### ISSUE TITLE
Clarify

### ISSUE THREAD

**Issue by HeChengHui** [Xuange923/Surveillance-Video-Understanding#2]
Hello, thank you for your work.

Just to check, if i want to use this dataset, i need to dwl UCF-Crime dataset first from [here](https://github.com/Xuange923/Surveillance-Video-Understanding?tab=readme-ov-file#original-ucf-crime-dataset-reference), then match the videos to the annotation in [here](https://github.com/Xuange923/Surveillance-Video-Understanding/tree/main/UCF%20Annotation)?

**Comment by Xuange923** [comment]
Yes, the annotations need to be matched with the video data to be used
